<a href="https://colab.research.google.com/github/Mohibl-6568/Fraudulent-Firm-Classification-A-Case-Study-of-an-External-Audit./blob/main/Fraudulent%20firm%20classification%3A%20A%20case%20study%20of%20an%20external%20audit.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv('audit_data.csv')

In [4]:
df.head()

Sector_score LOCATION_ID  PARA_A  Score_A  Risk_A  PARA_B  Score_B  Risk_B  \
0          3.89          23    4.18      0.6   2.508    2.50      0.2   0.500   
1          3.89           6    0.00      0.2   0.000    4.83      0.2   0.966   
2          3.89           6    0.51      0.2   0.102    0.23      0.2   0.046   
3          3.89           6    0.00      0.2   0.000   10.80      0.6   6.480   
4          3.89           6    0.00      0.2   0.000    0.08      0.2   0.016   

   TOTAL  numbers  ...  RiSk_E  History  Prob  Risk_F  Score  Inherent_Risk  \
0   6.68      5.0  ...     0.4        0   0.2     0.0    2.4          8.574   
1   4.83      5.0  ...     0.4        0   0.2     0.0    2.0          2.554   
2   0.74      5.0  ...     0.4        0   0.2     0.0    2.0          1.548   
3  10.80      6.0  ...     0.4        0   0.2     0.0    4.4         17.530   
4   0.08      5.0  ...     0.4        0   0.2     0.0    2.0          1.416   

   CONTROL_RISK  Detection_Risk  Audit_Risk  Risk  
0           0.4             0.5      1.7148     1  
1           0.4             0.5      0.5108     0  
2           0.4             0.5      0.3096     0  
3           0.4             0.5      3.5060     1  
4           0.4             0.5      0.2832     0  

[5 rows x 27 columns]

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 776 entries, 0 to 775
Data columns (total 27 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Sector_score    776 non-null    float64
 1   LOCATION_ID     776 non-null    object 
 2   PARA_A          776 non-null    float64
 3   Score_A         776 non-null    float64
 4   Risk_A          776 non-null    float64
 5   PARA_B          776 non-null    float64
 6   Score_B         776 non-null    float64
 7   Risk_B          776 non-null    float64
 8   TOTAL           776 non-null    float64
 9   numbers         776 non-null    float64
 10  Score_B.1       776 non-null    float64
 11  Risk_C          776 non-null    float64
 12  Money_Value     775 non-null    float64
 13  Score_MV        776 non-null    float64
 14  Risk_D          776 non-null    float64
 15  District_Loss   776 non-null    int64  
 16  PROB            776 non-null    float64
 17  RiSk_E          776 non-null    flo

In [6]:
df.describe().T

count       mean        std   min     25%     50%      75%  \
Sector_score    776.0  20.184536  24.319017  1.85  2.3700  3.8900  55.5700   
PARA_A          776.0   2.450194   5.678870  0.00  0.2100  0.8750   2.4800   
Score_A         776.0   0.351289   0.174055  0.20  0.2000  0.2000   0.6000   
Risk_A          776.0   1.351029   3.440447  0.00  0.0420  0.1750   1.4880   
PARA_B          776.0  10.799988  50.083624  0.00  0.0000  0.4050   4.1600   
Score_B         776.0   0.313144   0.169804  0.20  0.2000  0.2000   0.4000   
Risk_B          776.0   6.334008  30.072845  0.00  0.0000  0.0810   1.8405   
TOTAL           776.0  13.218481  51.312829  0.00  0.5375  1.3700   7.7075   
numbers         776.0   5.067655   0.264449  5.00  5.0000  5.0000   5.0000   
Score_B.1       776.0   0.223711   0.080352  0.20  0.2000  0.2000   0.2000   
Risk_C          776.0   1.152964   0.537417  1.00  1.0000  1.0000   1.0000   
Money_Value     775.0  14.137631  66.606519  0.00  0.0000  0.0900   5.5950   
Score_MV        776.0   0.290979   0.159745  0.20  0.2000  0.2000   0.4000   
Risk_D          776.0   8.265434  39.970849  0.00  0.0000  0.0180   2.2350   
District_Loss   776.0   2.505155   1.228678  2.00  2.0000  2.0000   2.0000   
PROB            776.0   0.206186   0.037508  0.20  0.2000  0.2000   0.2000   
RiSk_E          776.0   0.519072   0.290312  0.40  0.4000  0.4000   0.4000   
History         776.0   0.104381   0.531031  0.00  0.0000  0.0000   0.0000   
Prob            776.0   0.216753   0.067987  0.20  0.2000  0.2000   0.2000   
Risk_F          776.0   0.053608   0.305835  0.00  0.0000  0.0000   0.0000   
Score           776.0   2.702577   0.858923  2.00  2.0000  2.4000   3.2500   
Inherent_Risk   776.0  17.680612  54.740244  1.40  1.5835  2.2140  10.6635   
CONTROL_RISK    776.0   0.572680   0.444581  0.40  0.4000  0.4000   0.4000   
Detection_Risk  776.0   0.500000   0.000000  0.50  0.5000  0.5000   0.5000   
Audit_Risk      776.0   7.168158  38.667494  0.28  0.3167  0.5556   3.2499   
Risk            776.0   0.393041   0.488741  0.00  0.0000  0.0000   1.0000   

                      max  
Sector_score      59.8500  
PARA_A            85.0000  
Score_A            0.6000  
Risk_A            51.0000  
PARA_B          1264.6300  
Score_B            0.6000  
Risk_B           758.7780  
TOTAL           1268.9100  
numbers            9.0000  
Score_B.1          0.6000  
Risk_C             5.4000  
Money_Value      935.0300  
Score_MV           0.6000  
Risk_D           561.0180  
District_Loss      6.0000  
PROB               0.6000  
RiSk_E             2.4000  
History            9.0000  
Prob               0.6000  
Risk_F             5.4000  
Score              5.2000  
Inherent_Risk    801.2620  
CONTROL_RISK       5.8000  
Detection_Risk     0.5000  
Audit_Risk       961.5144  
Risk               1.0000

In [1]:
!pip install pyswarm

  Preparing metadata (setup.py) ... done
  Created wheel for pyswarm: filename=pyswarm-0.6-py3-none-any.whl size=4463 sha256=4a5083353b8398e5d159b722c2cc6fea42780f249473c839e8088a4d6100d2e1
  Stored in directory: /root/.cache/pip/wheels/bb/4f/ec/8970b83323e16aa95034da175454843947376614d6d5e9627f
Successfully built pyswarm


In [8]:
import numpy as np
import pandas as pd
from pyswarm import pso

X = df.drop(columns=["LOCATION_ID", "Risk"])
y = df["Risk"]

X = X.fillna(X.mean())

F = X.values  # Feature matrix (T x n)
alpha = y.values  # Target vector (T)

T, n = F.shape

def objective_function(w):
    error = 0
    for i in range(T):
        prediction = np.sum(w * F[i])
        error += (alpha[i] - prediction) ** 2
    return error

#Define bounds for each weight
lb = [-10] * n  # lower bound for each weight
ub = [10] * n   # upper bound for each weight

#Run PSO
best_weights, best_error = pso(objective_function, lb, ub, swarmsize=30, maxiter=100)

print("Best Weights found:", best_weights)
print("Best Error achieved:", best_error)


Stopping search: maximum iterations reached --> 100
Best Weights found: [  0.03877098   4.40376568   8.75735729  -5.68844207   1.1789324
   0.58188258  -2.57610833   2.91602734   5.38829707   0.37576395
   5.44768929   5.22071162  -4.57371384  -4.14453815  -6.27919186
   7.64321631 -10.          -3.54693435   3.25033502 -10.
  -5.38473566  -4.66326571   1.85748362  -8.20464312   0.46158257]
Best Error achieved: 168493.17145469098


In [9]:
# After running PSO and getting best_weights

# Step 1: Create a dataframe of features and their optimized weights
feature_importance = pd.DataFrame({
    "Feature": X.columns,
    "Weight": best_weights,
    "Abs_Weight": np.abs(best_weights)
})

# Step 2: Sort by absolute weight (importance)
feature_importance_sorted = feature_importance.sort_values(by="Abs_Weight", ascending=False)

# Step 3: Pick the top 9 features
top_9_features = feature_importance_sorted.head(9)

print("Top 9 features based on PSO optimization:")
print(top_9_features[["Feature", "Weight"]])


Top 9 features based on PSO optimization:
           Feature     Weight
16          RiSk_E -10.000000
19          Risk_F -10.000000
2          Score_A   8.757357
23  Detection_Risk  -8.204643
15            PROB   7.643216
14   District_Loss  -6.279192
3           Risk_A  -5.688442
10          Risk_C   5.447689
8          numbers   5.388297


In [10]:
top_9_feature_names = top_9_features["Feature"].tolist()

df_final = df[top_9_feature_names + ['Risk']]  # Also keep 'Risk' as target

# Now df_top9 contains only the important features + the Risk column
print(df_final.head())


   RiSk_E  Risk_F  Score_A  Detection_Risk  PROB  District_Loss  Risk_A  \
0     0.4     0.0      0.6             0.5   0.2              2   2.508   
1     0.4     0.0      0.2             0.5   0.2              2   0.000   
2     0.4     0.0      0.2             0.5   0.2              2   0.102   
3     0.4     0.0      0.2             0.5   0.2              2   0.000   
4     0.4     0.0      0.2             0.5   0.2              2   0.000   

   Risk_C  numbers  Risk  
0     1.0      5.0     1  
1     1.0      5.0     0  
2     1.0      5.0     0  
3     3.6      6.0     1  
4     1.0      5.0     0  


In [47]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score, f1_score, matthews_corrcoef, recall_score, precision_score, fbeta_score


# Prepare X and y
X = df_final.drop(columns=["Risk"])
y = df_final["Risk"]

# If Risk is continuous, we need to discretize it (optional)
# Example: If Risk is continuous, we can round it
# y = y.round().astype(int)

# Split into train/test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train a Decision Tree Classifier
model_dt = DecisionTreeClassifier(random_state=42)
model_dt.fit(X_train, y_train)

# Predict
y_pred = model_dt.predict(X_test)

# Confusion matrix
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(cm)
TP = cm[1, 1]
TN = cm[0, 0]
FP = cm[0, 1]
FN = cm[1, 0]
    # Type-I Error (False Positive Rate)
type_I_error_dt = FP / (FP + TN)
    # Type-II Error (False Negative Rate)
type_II_error_dt = FN / (FN + TP)
    # Sensitivity (Recall for positive class)
sensitivity_dt = TP / (TP + FN)
    # Specificity (Recall for negative class)
specificity_dt = TN / (TN + FP)
    # Accuracy
accuracy_dt = (TP + TN) / (TP + TN + FP + FN)
    # Error Rate
error_rate_dt = 1 - accuracy_dt
    # F1 Score
f1_dt = f1_score(y_test, y_pred)
    # F2 Score (heavily weight recall)
f2_dt = fbeta_score(y_test, y_pred, beta=2)
    # MCC
mcc_dt = matthews_corrcoef(y_test, y_pred)
print("\nMetrics:")
print(f"Type-I Error (False Positive Rate): {type_I_error_dt:.4f}")
print(f"Type-II Error (False Negative Rate): {type_II_error_dt:.4f}")
print(f"Sensitivity (Recall): {sensitivity_dt:.4f}")
print(f"Specificity: {specificity_dt:.4f}")
print(f"Accuracy: {accuracy_dt:.4f}")
print(f"Error Rate: {error_rate_dt:.4f}")
print(f"F1 Score: {f1_dt:.4f}")
print(f"F2 Score: {f2_dt:.4f}")
print(f"Matthews Correlation Coefficient (MCC): {mcc_dt:.4f}")

Confusion Matrix:
[[88  8]
 [12 48]]

Metrics:
Type-I Error (False Positive Rate): 0.0833
Type-II Error (False Negative Rate): 0.2000
Sensitivity (Recall): 0.8000
Specificity: 0.9167
Accuracy: 0.8718
Error Rate: 0.1282
F1 Score: 0.8276
F2 Score: 0.8108
Matthews Correlation Coefficient (MCC): 0.7268


In [46]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier  # <--- changed here
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score, f1_score, matthews_corrcoef, recall_score, precision_score, fbeta_score

# Prepare X and y
X = df_final.drop(columns=["Risk"])
y = df_final["Risk"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train a Random Forest Classifier
model_rf = RandomForestClassifier(random_state=42)
model_rf.fit(X_train, y_train)

# Predict
y_pred = model_rf.predict(X_test)

# Confusion matrix
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(cm)
TP = cm[1, 1]
TN = cm[0, 0]
FP = cm[0, 1]
FN = cm[1, 0]
# Type-I Error (False Positive Rate)
type_I_error_rf = FP / (FP + TN)

    # Type-II Error (False Negative Rate)
type_II_error_rf = FN / (FN + TP)

    # Sensitivity (Recall for positive class)
sensitivity_rf = TP / (TP + FN)

    # Specificity (Recall for negative class)
specificity_rf = TN / (TN + FP)

    # Accuracy
accuracy_rf = (TP + TN) / (TP + TN + FP + FN)

    # Error Rate
error_rate_rf = 1 - accuracy_rf

    # F1 Score
f1_rf = f1_score(y_test, y_pred)

    # F2 Score (favor recall more)
f2_rf = fbeta_score(y_test, y_pred, beta=2)

    # MCC
mcc_rf = matthews_corrcoef(y_test, y_pred)

    # Print all metrics
print("\nMetrics:")
print(f"Type-I Error (False Positive Rate): {type_I_error_rf:.4f}")
print(f"Type-II Error (False Negative Rate): {type_II_error_rf:.4f}")
print(f"Sensitivity (Recall): {sensitivity_rf:.4f}")
print(f"Specificity: {specificity_rf:.4f}")
print(f"Accuracy: {accuracy_rf:.4f}")
print(f"Error Rate: {error_rate_rf:.4f}")
print(f"F1 Score: {f1_rf:.4f}")
print(f"F2 Score: {f2_rf:.4f}")
print(f"Matthews Correlation Coefficient (MCC): {mcc_rf:.4f}")


Confusion Matrix:
[[88  8]
 [11 49]]

Metrics:
Type-I Error (False Positive Rate): 0.0833
Type-II Error (False Negative Rate): 0.1833
Sensitivity (Recall): 0.8167
Specificity: 0.9167
Accuracy: 0.8782
Error Rate: 0.1218
F1 Score: 0.8376
F2 Score: 0.8249
Matthews Correlation Coefficient (MCC): 0.7409


In [45]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score, f1_score, matthews_corrcoef, recall_score, precision_score, fbeta_score

# Prepare X and y
X = df_final.drop(columns=["Risk"])
y = df_final["Risk"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train a Neural Network (MLPClassifier)
model_nn = MLPClassifier(random_state=42, max_iter=1000)  # Increased max_iter for convergence
model_nn.fit(X_train, y_train)

# Predict
y_pred = model_nn.predict(X_test)

# Confusion matrix
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(cm)

# Extract values from the confusion matrix
TP = cm[1, 1]
TN = cm[0, 0]
FP = cm[0, 1]
FN = cm[1, 0]

# Type-I Error (False Positive Rate)
type_I_error_nn = FP / (FP + TN)

# Type-II Error (False Negative Rate)
type_II_error_nn = FN / (FN + TP)

# Sensitivity (Recall for positive class)
sensitivity_nn = TP / (TP + FN)

# Specificity (Recall for negative class)
specificity_nn = TN / (TN + FP)

# Accuracy
accuracy_nn = (TP + TN) / (TP + TN + FP + FN)

# Error Rate
error_rate_nn = 1 - accuracy_nn

# F1 Score
f1_nn = f1_score(y_test, y_pred)

# F2 Score (favor recall more)
f2_nn = fbeta_score(y_test, y_pred, beta=2)

# MCC
mcc_nn = matthews_corrcoef(y_test, y_pred)

# Print all metrics
print("\nMetrics:")
print(f"Type-I Error (False Positive Rate): {type_I_error_nn:.4f}")
print(f"Type-II Error (False Negative Rate): {type_II_error_nn:.4f}")
print(f"Sensitivity (Recall): {sensitivity_nn:.4f}")
print(f"Specificity: {specificity_nn:.4f}")
print(f"Accuracy: {accuracy_nn:.4f}")
print(f"Error Rate: {error_rate_nn:.4f}")
print(f"F1 Score: {f1_nn:.4f}")
print(f"F2 Score: {f2_nn:.4f}")
print(f"Matthews Correlation Coefficient (MCC): {mcc_nn:.4f}")


Confusion Matrix:
[[95  1]
 [11 49]]

Metrics:
Type-I Error (False Positive Rate): 0.0104
Type-II Error (False Negative Rate): 0.1833
Sensitivity (Recall): 0.8167
Specificity: 0.9896
Accuracy: 0.9231
Error Rate: 0.0769
F1 Score: 0.8909
F2 Score: 0.8448
Matthews Correlation Coefficient (MCC): 0.8405


In [44]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score, f1_score, matthews_corrcoef, recall_score, precision_score, fbeta_score

# Prepare X and y
X = df_final.drop(columns=["Risk"])
y = df_final["Risk"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train a Naive Bayes Classifier
model_nb = GaussianNB()
model_nb.fit(X_train, y_train)

# Predict
y_pred = model_nb.predict(X_test)

# Confusion matrix
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(cm)

# Extract values from the confusion matrix
TP = cm[1, 1]
TN = cm[0, 0]
FP = cm[0, 1]
FN = cm[1, 0]

# Type-I Error (False Positive Rate)
type_I_error_nb = FP / (FP + TN)

# Type-II Error (False Negative Rate)
type_II_error_nb = FN / (FN + TP)

# Sensitivity (Recall for positive class)
sensitivity_nb = TP / (TP + FN)

# Specificity (Recall for negative class)
specificity_nb = TN / (TN + FP)

# Accuracy
accuracy_nb = (TP + TN) / (TP + TN + FP + FN)

# Error Rate
error_rate_nb = 1 - accuracy_nb

# F1 Score
f1_nb = f1_score(y_test, y_pred)

# F2 Score (favor recall more)
f2_nb = fbeta_score(y_test, y_pred, beta=2)

# MCC
mcc_nb = matthews_corrcoef(y_test, y_pred)

# Print all metrics
print("\nMetrics:")
print(f"Type-I Error (False Positive Rate): {type_I_error_nb:.4f}")
print(f"Type-II Error (False Negative Rate): {type_II_error_nb:.4f}")
print(f"Sensitivity (Recall): {sensitivity_nb:.4f}")
print(f"Specificity: {specificity_nb:.4f}")
print(f"Accuracy: {accuracy_nb:.4f}")
print(f"Error Rate: {error_rate_nb:.4f}")
print(f"F1 Score: {f1_nb:.4f}")
print(f"F2 Score: {f2_nb:.4f}")
print(f"Matthews Correlation Coefficient (MCC): {mcc_nb:.4f}")


Confusion Matrix:
[[96  0]
 [21 39]]

Metrics:
Type-I Error (False Positive Rate): 0.0000
Type-II Error (False Negative Rate): 0.3500
Sensitivity (Recall): 0.6500
Specificity: 1.0000
Accuracy: 0.8654
Error Rate: 0.1346
F1 Score: 0.7879
F2 Score: 0.6989
Matthews Correlation Coefficient (MCC): 0.7303


In [43]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score, f1_score, matthews_corrcoef, recall_score, precision_score, fbeta_score

# Prepare X and y
X = df_final.drop(columns=["Risk"])
y = df_final["Risk"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train a Support Vector Machine (SVM)
model_svm = SVC(random_state=42, kernel='linear')  # You can use 'linear', 'rbf', etc.
model_svm.fit(X_train, y_train)

# Predict
y_pred = model_svm.predict(X_test)

# Confusion matrix
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(cm)

# Extract values from the confusion matrix
TP = cm[1, 1]
TN = cm[0, 0]
FP = cm[0, 1]
FN = cm[1, 0]

# Type-I Error (False Positive Rate)
type_I_error_svm = FP / (FP + TN)

# Type-II Error (False Negative Rate)
type_II_error_svm = FN / (FN + TP)

# Sensitivity (Recall for positive class)
sensitivity_svm = TP / (TP + FN)

# Specificity (Recall for negative class)
specificity_svm = TN / (TN + FP)

# Accuracy
accuracy_svm = (TP + TN) / (TP + TN + FP + FN)

# Error Rate
error_rate_svm = 1 - accuracy_svm

# F1 Score
f1_svm = f1_score(y_test, y_pred)

# F2 Score (favor recall more)
f2_svm = fbeta_score(y_test, y_pred, beta=2)

# MCC
mcc_svm = matthews_corrcoef(y_test, y_pred)

# Print all metrics
print("\nMetrics:")
print(f"Type-I Error (False Positive Rate): {type_I_error_svm:.4f}")
print(f"Type-II Error (False Negative Rate): {type_II_error_svm:.4f}")
print(f"Sensitivity (Recall): {sensitivity_svm:.4f}")
print(f"Specificity: {specificity_svm:.4f}")
print(f"Accuracy: {accuracy_svm:.4f}")
print(f"Error Rate: {error_rate_svm:.4f}")
print(f"F1 Score: {f1_svm:.4f}")
print(f"F2 Score: {f2_svm:.4f}")
print(f"Matthews Correlation Coefficient (MCC): {mcc_svm:.4f}")


Confusion Matrix:
[[95  1]
 [10 50]]

Metrics:
Type-I Error (False Positive Rate): 0.0104
Type-II Error (False Negative Rate): 0.1667
Sensitivity (Recall): 0.8333
Specificity: 0.9896
Accuracy: 0.9295
Error Rate: 0.0705
F1 Score: 0.9009
F2 Score: 0.8591
Matthews Correlation Coefficient (MCC): 0.8535


In [41]:
# Create a list of model names and their corresponding metrics
models = ['Decision Tree', 'Random Forest', 'Neural Network', 'Naive Bayes', 'SVM']
type_I_errors = [type_I_error_dt, type_I_error_rf, type_I_error_nn, type_I_error_nb, type_I_error_svm]
type_II_errors = [type_II_error_dt, type_II_error_rf, type_II_error_nn, type_II_error_nb, type_II_error_svm]
sensitivities = [sensitivity_dt, sensitivity_rf, sensitivity_nn, sensitivity_nb, sensitivity_svm]
specificities = [specificity_dt, specificity_rf, specificity_nn, specificity_nb, specificity_svm]
accuracies = [accuracy_dt, accuracy_rf, accuracy_nn, accuracy_nb, accuracy_svm]
error_rates = [error_rate_dt, error_rate_rf, error_rate_nn, error_rate_nb, error_rate_svm]
f1_scores = [f1_dt, f1_rf, f1_nn, f1_nb, f1_svm]
f2_scores = [f2_dt, f2_rf, f2_nn, f2_nb, f2_svm]
mcc_scores = [mcc_dt, mcc_rf, mcc_nn, mcc_nb, mcc_svm]

# Create a DataFrame
metrics_df = pd.DataFrame({
    'Model': models,
    'Type I Error': type_I_errors,
    'Type II Error': type_II_errors,
    'Sensitivity': sensitivities,
    'Specificity': specificities,
    'Accuracy': accuracies,
    'Error Rate': error_rates,
    'F1 Score': f1_scores,
    'F2 Score': f2_scores,
    'MCC': mcc_scores
})

# Display the DataFrame
metrics_df


Model  Type I Error  Type II Error  Sensitivity  Specificity  \
0   Decision Tree      0.083333       0.183333     0.816667     0.916667   
1   Random Forest      0.083333       0.183333     0.816667     0.916667   
2  Neural Network      0.010417       0.183333     0.816667     0.989583   
3     Naive Bayes      0.000000       0.350000     0.650000     1.000000   
4             SVM      0.010417       0.166667     0.833333     0.989583   

   Accuracy  Error Rate  F1 Score  F2 Score       MCC  
0  0.878205    0.128205  0.827586  0.810811  0.726833  
1  0.878205    0.121795  0.837607  0.824916  0.740897  
2  0.923077    0.076923  0.890909  0.844828  0.840510  
3  0.865385    0.134615  0.787879  0.698925  0.730297  
4  0.929487    0.070513  0.900901  0.859107  0.853468

In [ ]:
print("\nEnter values for prediction:")
input_features = []
# Assuming you know the number of features in X, you can use the following loop to get user input
for column in X.columns:
    value = float(input(f"Enter value for {column}: "))
    input_features.append(value)

# Convert the input list to a DataFrame (match the column names of the original dataset)
input_df = pd.DataFrame([input_features], columns=X.columns)

# Predict the risk
predicted_risk = model_svm.predict(input_df)
print(f"\nPredicted Risk: {predicted_risk[0]}")